### ISSUE TITLE
My friend's stream badge has never worked

### ISSUE THREAD

**Issue by gitmanbro** [svinkle/streambadge#16]
Channel: http://www.hitbox.tv/CptSledge
Badge: http://streambadge.com/hitbox/CptSledge.png

I've tried it with and without uppercase letters and over a period of weeks. Never seems to update with his avatar and never shows online status. Please help.

**Comment by svinkle** [comment]
This is the URL which grabs the data: http://api.hitbox.tv/media/live/[username]

For some reason nothing is returned for http://api.hitbox.tv/media/live/cptsledge

Not sure what to tell you. Might be an issue with the hitbox API. Try a different account?

**Comment by gitmanbro** [comment]
Interesting... I'll take my issue to hitbox.tv in that case! Thank you svinkle.
