### ISSUE TITLE
Fix cache headers

### ISSUE THREAD

**Issue by MadMakz** [svinkle/streambadge#17]
Basicaly it's repoening #1 

    Cache-Control: max-age=2592000
    Expires: Tue, 24 Mar 2015 23:40:59 GMT

The image got first time called today.

**PS:** Be aware of the fact that *max-age*, by [standart](https://tools.ietf.org/html/rfc7234#section-5.3), overwrites *expires*.

**Comment by svinkle** [comment]
Yep, that doesn't make sense to have that. Just set all media expires to 0 seconds.
